version: "3"
services:
    cantaloupe:
        build: .
        container_name: ${PROJECT_NAME}_cantaloupe
        image: swissartresearx/cantaloupe:5.0
        ports:
            - ${PORT_CANTALOUPE}:8182
        volumes:
            - ./config:/config
            - ./images:/images
    jobs:
        build: ./services/jobs
        container_name: ${PROJECT_NAME}_jobs
        image: idsarideploy01.uzh.ch/swissartresearx/sari-cantaloupe-bso-jobs
        volumes:
          - ./data:/data
          - ./images:/images
          - ./scripts:/scripts
