version: "3"
services:
    cantaloupe-image-proxy:
        environment:
            LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
            LETSENCRYPT_HOST: ${LETSENCRYPT_ORIGINAL_IMAGE_HOST}
            VIRTUAL_HOST: ${LETSENCRYPT_ORIGINAL_IMAGE_HOST}
            VIRTUAL_PORT: 80
        image: nginx
        restart: unless-stopped
        volumes:
            - ./images:/usr/share/nginx/html
        networks:
        - proxy